# PyInstaller Spec File generated for Motor HPR

a = Analysis(
    ['src/desktop/app.py'],
    pathext=['.py'],
    binaries=[],
    datas=[
        ('src/data/ceo_knowledge_base.json', '.'),
        ('src/desktop/assets/hpr.ico', 'src/desktop/assets'),
        ('src/desktop/assets/hpr_logo.png', 'src/desktop/assets'),
        ('src/core/engine.py', 'src/core'),
        ('src/core/triage.py', 'src/core'),
        ('src/core/security_agent.py', 'src/core'),
        ('src/desktop/agent.py', 'src/desktop'),
        ('src/desktop/voice.py', 'src/desktop'),
        ('src/models/contracts.py', 'src/models'),
    ),
    hiddenimports=[
        'customtkinter',
        'PIL',
        'pyttsx3',
        'json',
        'os',
        'sys',
        're',
        'threading',
        'collections',
        'dataclasses',
    ],
    hookspath=[],
    hooksdir=(),
    runtime_hooks=[],
    together_fragments=[],
    together_cores=[],
    noarchive=False,
    lib=None,
    pickle_bin='0',
    ascii=False,
    parent,
    )

p = PYTHONAPP(
    a,
    tree_name='',
    company_name='HPR Project',
    copyright='Copyright (c) 2026 HPR Project',
    comment='Motor HPR - Escritorio Local',
    version='2.0.0',
    series='HPR',
    wine_os='',
    uac_admin=False,
    uac_uiaccess=False,
    name='Motor HPR',
)